"""Initial tables

Revision ID: 3a94565cc417
Revises: 
Create Date: 2025-08-13 18:01:06.791378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a94565cc417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neighborhoods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('neighborhood_id', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('surface_total', sa.Integer(), nullable=True),
    sa.Column('garages', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('currency_price', sa.String(length=3), nullable=True),
    sa.Column('expenses', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('currency_expenses', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("currency_expenses IN ('ARS', 'USD')"),
    sa.CheckConstraint("currency_price IN ('ARS', 'USD')"),
    sa.CheckConstraint("property_type IN ('department', 'house', 'duplex', 'ph')"),
    sa.CheckConstraint("source IN ('argenprop', 'zonaprop', 'mercadolibre', 'cabaprop')"),
    sa.CheckConstraint('bathrooms >= 0'),
    sa.CheckConstraint('bedrooms >= 0'),
    sa.CheckConstraint('expenses >= 0'),
    sa.CheckConstraint('price >= 0'),
    sa.CheckConstraint('rooms >= 0'),
    sa.CheckConstraint('surface_total >= 0'),
    sa.ForeignKeyConstraint(['neighborhood_id'], ['neighborhoods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    op.drop_table('neighborhoods')
    # ### end Alembic commands ###
