"""add locality and link to neighborhoods

Revision ID: 60d9b900d64f
Revises: e67ac4de4df3
Create Date: 2025-10-06 16:44:34.286318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d9b900d64f'
down_revision: Union[str, Sequence[str], None] = 'e67ac4de4df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('neighborhoods', sa.Column('locality_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'neighborhoods', 'localities', ['locality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'neighborhoods', type_='foreignkey')
    op.drop_column('neighborhoods', 'locality_id')
    op.drop_table('localities')
    # ### end Alembic commands ###
